# Generated by Django 2.0.6 on 2018-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WechatArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('cover', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('like_num', models.IntegerField(default=0)),
                ('read_num', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('url', models.URLField()),
                ('recieve_time', models.DateTimeField()),
                ('account', models.CharField(max_length=20)),
                ('biz', models.CharField(max_length=50)),
            ],
        ),
    ]
